package designs;

import java.awt.Color;

public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        newOrder = new javax.swing.JPanel();
        newOrderLabel = new javax.swing.JLabel();
        medicineDetails = new javax.swing.JPanel();
        medicineDetailsLabel = new javax.swing.JLabel();
        customerDetails = new javax.swing.JPanel();
        customerDetailsLabel = new javax.swing.JLabel();
        newMedicine = new javax.swing.JPanel();
        newMedicineLabel = new javax.swing.JLabel();
        newCustomer = new javax.swing.JPanel();
        newCustomerLabel = new javax.swing.JLabel();
        orderDetails = new javax.swing.JPanel();
        newMedicineLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 50));
        setSize(new java.awt.Dimension(1280, 720));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(240, 151, 57));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(240, 151, 57));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Shrikhand", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DASHBOARD");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 280, 70));

        jLabel5.setBackground(new java.awt.Color(240, 151, 57));
        jLabel5.setFont(new java.awt.Font("Lucida Handwriting", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Central Medico");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 340, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 80));

        jPanel3.setBackground(new java.awt.Color(13, 36, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(13, 36, 51));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        newOrder.setBackground(new java.awt.Color(13, 36, 51));
        newOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newOrderMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newOrderMousePressed(evt);
            }
        });

        newOrderLabel.setBackground(new java.awt.Color(255, 255, 255));
        newOrderLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newOrderLabel.setForeground(new java.awt.Color(255, 255, 255));
        newOrderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newOrderLabel.setText("New Order");

        javax.swing.GroupLayout newOrderLayout = new javax.swing.GroupLayout(newOrder);
        newOrder.setLayout(newOrderLayout);
        newOrderLayout.setHorizontalGroup(
            newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newOrderLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(newOrderLabel)
                .addContainerGap())
        );
        newOrderLayout.setVerticalGroup(
            newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newOrderLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(newOrderLabel)
                .addGap(15, 15, 15))
        );

        medicineDetails.setBackground(new java.awt.Color(13, 36, 51));
        medicineDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medicineDetailsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                medicineDetailsMousePressed(evt);
            }
        });

        medicineDetailsLabel.setBackground(new java.awt.Color(255, 255, 255));
        medicineDetailsLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        medicineDetailsLabel.setForeground(new java.awt.Color(255, 255, 255));
        medicineDetailsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medicineDetailsLabel.setText("Medicine Details");

        javax.swing.GroupLayout medicineDetailsLayout = new javax.swing.GroupLayout(medicineDetails);
        medicineDetails.setLayout(medicineDetailsLayout);
        medicineDetailsLayout.setHorizontalGroup(
            medicineDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, medicineDetailsLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(medicineDetailsLabel)
                .addContainerGap())
        );
        medicineDetailsLayout.setVerticalGroup(
            medicineDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicineDetailsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(medicineDetailsLabel)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        customerDetails.setBackground(new java.awt.Color(13, 36, 51));
        customerDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerDetailsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                customerDetailsMousePressed(evt);
            }
        });

        customerDetailsLabel.setBackground(new java.awt.Color(255, 255, 255));
        customerDetailsLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        customerDetailsLabel.setForeground(new java.awt.Color(255, 255, 255));
        customerDetailsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerDetailsLabel.setText("Customer Details");

        javax.swing.GroupLayout customerDetailsLayout = new javax.swing.GroupLayout(customerDetails);
        customerDetails.setLayout(customerDetailsLayout);
        customerDetailsLayout.setHorizontalGroup(
            customerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerDetailsLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(customerDetailsLabel)
                .addContainerGap())
        );
        customerDetailsLayout.setVerticalGroup(
            customerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerDetailsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(customerDetailsLabel)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        newMedicine.setBackground(new java.awt.Color(13, 36, 51));
        newMedicine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newMedicineMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newMedicineMousePressed(evt);
            }
        });

        newMedicineLabel.setBackground(new java.awt.Color(255, 255, 255));
        newMedicineLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newMedicineLabel.setForeground(new java.awt.Color(255, 255, 255));
        newMedicineLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newMedicineLabel.setText("Modify Medicine");

        javax.swing.GroupLayout newMedicineLayout = new javax.swing.GroupLayout(newMedicine);
        newMedicine.setLayout(newMedicineLayout);
        newMedicineLayout.setHorizontalGroup(
            newMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newMedicineLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(newMedicineLabel)
                .addContainerGap())
        );
        newMedicineLayout.setVerticalGroup(
            newMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newMedicineLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(newMedicineLabel)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        newCustomer.setBackground(new java.awt.Color(13, 36, 51));
        newCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newCustomerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newCustomerMousePressed(evt);
            }
        });

        newCustomerLabel.setBackground(new java.awt.Color(255, 255, 255));
        newCustomerLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newCustomerLabel.setForeground(new java.awt.Color(255, 255, 255));
        newCustomerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newCustomerLabel.setText("Modify Customer");

        javax.swing.GroupLayout newCustomerLayout = new javax.swing.GroupLayout(newCustomer);
        newCustomer.setLayout(newCustomerLayout);
        newCustomerLayout.setHorizontalGroup(
            newCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newCustomerLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(newCustomerLabel)
                .addContainerGap())
        );
        newCustomerLayout.setVerticalGroup(
            newCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newCustomerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(newCustomerLabel)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        orderDetails.setBackground(new java.awt.Color(13, 36, 51));
        orderDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderDetailsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                orderDetailsMousePressed(evt);
            }
        });

        newMedicineLabel1.setBackground(new java.awt.Color(255, 255, 255));
        newMedicineLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newMedicineLabel1.setForeground(new java.awt.Color(255, 255, 255));
        newMedicineLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newMedicineLabel1.setText("Order Details");

        javax.swing.GroupLayout orderDetailsLayout = new javax.swing.GroupLayout(orderDetails);
        orderDetails.setLayout(orderDetailsLayout);
        orderDetailsLayout.setHorizontalGroup(
            orderDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderDetailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newMedicineLabel1)
                .addContainerGap())
        );
        orderDetailsLayout.setVerticalGroup(
            orderDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderDetailsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(newMedicineLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(orderDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medicineDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newMedicine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {customerDetails, medicineDetails, newCustomer, newMedicine, newOrder});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(newOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(medicineDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(orderDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {customerDetails, medicineDetails, newCustomer, newMedicine, newOrder});

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 210, 470));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 640));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 1070, 640));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newOrderMouseClicked
        // TODO add your handling code here:
        OrderDetailsForm orderDetailsForm = new OrderDetailsForm();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(orderDetailsForm).setVisible(true);
    }//GEN-LAST:event_newOrderMouseClicked

    private void newOrderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newOrderMousePressed
        // TODO add your handling code here:
        newOrder.setBackground(new Color(240, 151, 57));
        medicineDetails.setBackground(new Color(13, 36, 51));
        customerDetails.setBackground(new Color(13, 36, 51));
        newMedicine.setBackground(new Color(13, 36, 51));
        newCustomer.setBackground(new Color(13, 36, 51));  
        orderDetails.setBackground(new Color(13, 36, 51));
    }//GEN-LAST:event_newOrderMousePressed

    private void medicineDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicineDetailsMouseClicked
        // TODO add your handling code here:
        MedicineReport medicineReport = new MedicineReport();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(medicineReport).setVisible(true);
    }//GEN-LAST:event_medicineDetailsMouseClicked

    private void medicineDetailsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicineDetailsMousePressed
        // TODO add your handling code here:
        newOrder.setBackground(new Color(13, 36, 51));
        medicineDetails.setBackground(new Color(240, 151, 57));
        customerDetails.setBackground(new Color(13, 36, 51));
        newMedicine.setBackground(new Color(13, 36, 51));
        newCustomer.setBackground(new Color(13, 36, 51));
        orderDetails.setBackground(new Color(13, 36, 51));
    }//GEN-LAST:event_medicineDetailsMousePressed

    private void customerDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerDetailsMouseClicked
        // TODO add your handling code here:
        CustomerReport customerReport = new CustomerReport();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(customerReport).setVisible(true);
    }//GEN-LAST:event_customerDetailsMouseClicked

    private void customerDetailsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerDetailsMousePressed
        // TODO add your handling code here:
        newOrder.setBackground(new Color(13, 36, 51));
        medicineDetails.setBackground(new Color(13, 36, 51));
        customerDetails.setBackground(new Color(240, 151, 57));
        newMedicine.setBackground(new Color(13, 36, 51));
        newCustomer.setBackground(new Color(13, 36, 51));
        orderDetails.setBackground(new Color(13, 36, 51));
    }//GEN-LAST:event_customerDetailsMousePressed

    private void newMedicineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newMedicineMouseClicked
        // TODO add your handling code here:
        MedicineMasterForm medicineMasterForm = new MedicineMasterForm();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(medicineMasterForm).setVisible(true);
    }//GEN-LAST:event_newMedicineMouseClicked

    private void newMedicineMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newMedicineMousePressed
        // TODO add your handling code here:
        newOrder.setBackground(new Color(13, 36, 51));
        medicineDetails.setBackground(new Color(13, 36, 51));
        customerDetails.setBackground(new Color(13, 36, 51));
        newMedicine.setBackground(new Color(240, 151, 57));
        newCustomer.setBackground(new Color(13, 36, 51));
        orderDetails.setBackground(new Color(13, 36, 51));
    }//GEN-LAST:event_newMedicineMousePressed

    private void newCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newCustomerMouseClicked
        // TODO add your handling code here:
        CustomerMasterForm customerMasterForm = new CustomerMasterForm();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(customerMasterForm).setVisible(true);
    }//GEN-LAST:event_newCustomerMouseClicked

    private void newCustomerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newCustomerMousePressed
        // TODO add your handling code here:
        newOrder.setBackground(new Color(13, 36, 51));
        medicineDetails.setBackground(new Color(13, 36, 51));
        customerDetails.setBackground(new Color(13, 36, 51));
        newMedicine.setBackground(new Color(13, 36, 51));
        newCustomer.setBackground(new Color(240, 151, 57));
        orderDetails.setBackground(new Color(13, 36, 51));
    }//GEN-LAST:event_newCustomerMousePressed

    private void orderDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderDetailsMouseClicked
        // TODO add your handling code here:
        OrderReport orderReport = new OrderReport();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(orderReport).setVisible(true);
    }//GEN-LAST:event_orderDetailsMouseClicked

    private void orderDetailsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderDetailsMousePressed
        // TODO add your handling code here:
        newOrder.setBackground(new Color(13, 36, 51));
        medicineDetails.setBackground(new Color(13, 36, 51));
        customerDetails.setBackground(new Color(13, 36, 51));
        newMedicine.setBackground(new Color(13, 36, 51));
        newCustomer.setBackground(new Color(13, 36, 51));        
        orderDetails.setBackground(new Color(240, 151, 57));
    }//GEN-LAST:event_orderDetailsMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel customerDetails;
    private javax.swing.JLabel customerDetailsLabel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel medicineDetails;
    private javax.swing.JLabel medicineDetailsLabel;
    private javax.swing.JPanel newCustomer;
    private javax.swing.JLabel newCustomerLabel;
    private javax.swing.JPanel newMedicine;
    private javax.swing.JLabel newMedicineLabel;
    private javax.swing.JLabel newMedicineLabel1;
    private javax.swing.JPanel newOrder;
    private javax.swing.JLabel newOrderLabel;
    private javax.swing.JPanel orderDetails;
    // End of variables declaration//GEN-END:variables
}
